# yamllint configuration for cursor-rules
extends: default

rules:
  line-length:
    max: 120
    level: warning
  
  indentation:
    spaces: 2
    indent-sequences: true
  
  comments:
    min-spaces-from-content: 1
  
  document-start: disable
  
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']

ignore: |
  node_modules/
  .git/
  dist/
  coverage/
