name: CI

on:
    push:
        branches: [main, dev]
    pull_request:
        branches: [main, dev]

permissions:
    contents: read

jobs:
    go-lint-test:
        name: Go Lint & Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version: "1.24.x"

            - name: Cache Go build
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.cache/go-build
                      ~/go/pkg/mod
                  key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
                  restore-keys: |
                      ${{ runner.os }}-go-

            - name: Vet
              run: go vet ./...

            - name: Test (race + cover)
              run: go test -race -coverprofile=coverage.out ./...

            - name: Upload coverage
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: coverage
                  path: coverage.out

    functional-integration:
        name: Functional Integration
        runs-on: ubuntu-latest
        needs: go-lint-test
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version: "1.24.x"

            - name: Run integration script
              run: |
                  chmod +x ./scripts/integration_test.sh
                  ./scripts/integration_test.sh

            - name: Upload integration logs
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: integration-logs
                  path: /tmp/*cursor-rules*.log

    #extension:
    #    name: VSCode Extension Build & Test
    #    runs-on: ubuntu-latest
    #    needs: go-lint-test
    #    steps:
    #        - name: Checkout
    #          uses: actions/checkout@v4
#
    #        - name: Use Node.js
    #          uses: actions/setup-node@v4
    #          with:
    #              node-version: "20"
#
    #        #- name: Install deps
    #        #  run: |
    #        #      cd extension
    #        #      npm install
    #        #
    #        #name: Build extension
    #        #run: |
    #        #   cd extension
    #        #   npm run build
    #        # 
    #        #- name: Test extension
    #        #  run: |
    #        #      cd extension
    #        #      npm test
