name: CI

on:
  push:
    branches: [ main, feat/* ]
  pull_request:
    branches: [ main ]

env:
  GO_VERSION_FILE: go.mod

jobs:
  test-go:
    name: Test Go application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{ env.GO_VERSION_FILE }}
          cache: true

      - name: Download dependencies
        run: go mod download

      - name: Run vet
        run: go vet ./...

      - name: Run tests
        run: make test

      - name: Build binary
        run: make build

  lint-go:
    name: Lint Go code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{ env.GO_VERSION_FILE }}
          cache: true

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout=10m

  integration-test:
    name: Integration tests
    runs-on: ubuntu-latest
    needs: [test-go]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{ env.GO_VERSION_FILE }}
          cache: true

      - name: Run integration tests
        run: scripts/integration_test.sh

  build-extension:
    name: Build VSCode extension
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Install extension dependencies
        working-directory: extension
        run: pnpm install --no-frozen-lockfile

      - name: Build extension
        working-directory: extension
        run: pnpm build

      - name: Package VSIX
        working-directory: extension
        run: npx @vscode/vsce package --no-dependencies

      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: cursor-rules-extension
          path: extension/*.vsix
          retention-days: 30
