name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Install pnpm
        run: |
          curl -fsSL https://get.pnpm.io/install.sh | sh -
          export PATH="$$HOME/.local/share/pnpm:${PATH}"
      - name: Run go test
        run: go test ./...
      - name: Run go vet
        run: go vet ./...
      - name: Build CLI
        run: make build

